git clone --depth 1 https://github.com.cnpmjs.org/defnull/bottle third_party/ycmd/third_party/bottle
git clone --depth 1 https://github.com.cnpmjs.org/ycm-core/regex.git third_party/ycmd/third_party/cregex
git clone --depth 1 https://github.com.cnpmjs.org/davidhalter/jedi third_party/ycmd/third_party/jedi_deps/jedi
git clone --depth 1 https://github.com.cnpmjs.org/numpy/numpydoc third_party/ycmd/third_party/jedi_deps/numpydoc
git clone --depth 1 https://github.com.cnpmjs.org/davidhalter/parso third_party/ycmd/third_party/jedi_deps/parso
git clone --depth 1 https://github.com.cnpmjs.org/certifi/python-certifi third_party/ycmd/third_party/requests_deps/certifi
git clone --depth 1 https://github.com.cnpmjs.org/chardet/chardet third_party/ycmd/third_party/requests_deps/chardet
git clone --depth 1 https://github.com.cnpmjs.org/kjd/idna third_party/ycmd/third_party/requests_deps/idna
git clone --depth 1 https://github.com.cnpmjs.org/requests/requests third_party/ycmd/third_party/requests_deps/requests
git clone --depth 1 https://github.com.cnpmjs.org/urllib3/urllib3 third_party/ycmd/third_party/requests_deps/urllib3
git clone --depth 1 https://github.com.cnpmjs.org/Pylons/waitress third_party/ycmd/third_party/waitress
git clone --depth 1 https://github.com.cnpmjs.org/gorakhargosh/pathtools third_party/ycmd/third_party/watchdog_deps/pathtools
git clone --depth 1 https://github.com.cnpmjs.org/gorakhargosh/watchdog third_party/ycmd/third_party/watchdog_deps/watchdog
