#!/usr/bin/perl
require 5.6.0;
use strict;
use Socket;
use FileHandle;

my ($this, $now);
my $port = shift || 29688;

$this = pack('Sna4x8', AF_INET, $port, "\0\0\0\0");
print "Port = $port\n";
my $prototype = getprotobyname('tcp');
socket(SOCKET, PF_INET, SOCK_STREAM, $prototype) 
   or  die "socket: $!\n";
print "Socket ok.\n";

bind(SOCKET, $this) or die "bind: $!\n";
print "Bind ok.\n";

listen(SOCKET, SOMAXCONN)  or die "connect: $!\n";
print "Listen ok.\n";

#COMM_SOCKET->autoflush;
#SOCKET->autoflush;

while (1) {
   print "In loop.\n";
   accept(COMM_SOCKET, SOCKET) or die "$!\n";
   print "Accept ok.\n";
   $now = time;
   print $now;
   print COMM_SOCKET $now;
}
