set lispwords+=defcommand
set lispwords-=if
set lispwords+=set-dispatch-macro-character
set lispwords+=get-dispatch-macro-character
set lispwords+=defrule
setlocal dictionary=~/.sbcl_completions
setlocal complete+=k
setlocal equalprg=emacs\ --script\ ~/.vim/bin/emacsformat
setlocal omnifunc=MyComplete
